//
//  BusinessesViewModel.swift
//  Here's Hingham!
//
//  Created by Cameron Conway on 5/7/25.
//

import Foundation
import MapKit
import SwiftUI
import SwiftData

class BusinessesViewModel: ObservableObject {
  @Published var mapCameraPosition: MapCameraPosition = MapCameraPosition.region(MKCoordinateRegion(center: CLLocationCoordinate2D(latitude: 42.23227,longitude: -70.89828), span: MKCoordinateSpan(latitudeDelta: 0.1, longitudeDelta: 0.1)))
  
  @Published var businesses: [SchemaV1.Business] = [
    SchemaV1.Business(address: "116 North St", areaId: "Hingham Square", desc: "Pub", googleId: "ChIJuRiK_Eth44kR7RYIx3CeSws", googleRating: 4.6, googleReviews: 365, googleUrl: "https://maps.app.goo.gl/J9sDsqbfxhjSN9sC8", hours: "0,12PM-12AM;1,12PM-12AM;2,12PM-12AM;3,12PM-12AM;4,12PM-12AM;5,12PM-12AM;6,12PM-12AM", imageCount: 6, likes: 0, locationLat: 42.24265, locationLng: -70.88871, name: "The Snug", nickname: "", notes: "Known as the “Home of the Perfect Pint.” A quaint, yet exciting, Irish style pub in Hingham Square offering lunch and dinner menus as well as excellent local and Irish entertainment. The Snug features a “state of the art” European draft beer system second to none. While visiting The Snug please be sure to say hello to the owners Ed & Ellen (Nally) Brown, who graciously await your arrival.", phone: "781-749-9774", shortName: "Pub", type: 1, website: "https://www.snugpub.com/", yelpCategory: "Pubs", yelpId: "the-snug-hingham", yelpPrice: "$$", yelpRating: 3.9, yelpReviews: 141, yelpUrl: "https://www.yelp.com/biz/the-snug-hingham?adjust_creative=oMiPYzoO1rgsBWiS9cnBrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=oMiPYzoO1rgsBWiS9cnBrQ"),
    SchemaV1.Business(address: "118 North St", areaId: "Hingham Square", desc: "Liquor", googleId: "ChIJTc1i_kth44kRAao7Yv_4Q1Y", googleRating: 4.4, googleReviews: 22, googleUrl: "https://maps.app.goo.gl/3he63uQ2T8hLSW429", hours: "0,10AM-6PM;1,8AM-9:30PM;2,8AM-9:30PM;3,8AM-9:30PM;4,8AM-9:30PM;5,8AM-9:30PM;6,8AM-9:30PM", imageCount: 1, likes: 0, locationLat: 42.242628, locationLng: -70.88894, name: "Hennessy News & Liquors", nickname: "", notes: "<div><strong>Hours</strong></div><br/>\n<div style=\"white-space:pre\">\nSunday&#9;6:00 AM - 6:00 PM\nMonday&#9;6:00 AM - 10:00 PM\nTuesday&#9;6:00 AM - 10:00 PM\nWednesday&#9;6:00 AM - 10:00 PM\nThursday&#9;6:00 AM - 10:00 PM\nFriday&#9;&#9;6:00 AM - 10:00 PM\nSaturday&#9;6:00 AM - 10:00 PM\n</div>\n", phone: "(781) 749-7528", shortName: "Liquor", type: 2, website: "https://maps.app.goo.gl/3he63uQ2T8hLSW429", yelpCategory: "Beer, Wine & Spirits", yelpId: "hingham-liquors-hingham", yelpPrice: "$$", yelpRating: 5, yelpReviews: 1, yelpUrl: "https://www.yelp.com/biz/hingham-liquors-hingham"),
    SchemaV1.Business(address: "132 North St", areaId: "Hingham Square", desc: "Gifts", googleId: "ChIJ2ZNcVUlh44kR6xkGRtx_cpY", googleRating: 5, googleReviews: 7, googleUrl: "https://maps.app.goo.gl/hUkJpa6DXpTaxUJL6", hours: "0,12-4PM;1,10AM-5PM;2,10AM-5PM;3,10AM-5PM;4,10AM-5PM;5,10AM-5PM;6,10AM-5PM", imageCount: 1, likes: 0, locationLat: 42.24254, locationLng: -70.88912, name: "Acquire Good", nickname: "", notes: "From the founder:<br/><br/>\"Acquire Good set out on a journey to bring a fun, familiar and simple gifting experience to the South Shore.  After an 11 year career in the sports and entertainment industry, I decided to dive into a new opportunity.  The idea of meeting a customer and finding the perfect gift for that special occasion is pretty amazing.<br/><br/>I am fortunate to occupy a space that has housed a retail store since the late 80’s.  I am forever grateful to those who came before me and allowed this local business to thrive.  Over the years, the various stores at 132 North Street  have evolved to meet the demands and needs of the local customers.  I am excited to keep the products that the town has come to love over the years as well as add a new funky twist to the boutique.  I couldn’t be happier that you love our products as much as I do and I am forever grateful for the opportunity to share a few of my favorite things with you.\"", phone: "(781) 749-5111", shortName: "Gifts", type: 2, website: "https://acquiregood.com/", yelpCategory: "Gift Shops, Jewelry, Home Decor", yelpId: "acquire-good-hingham", yelpPrice: "$$", yelpRating: 5, yelpReviews: 3,  yelpUrl: "https://www.yelp.com/biz/acquire-good-hingham?adjust_creative=oMiPYzoO1rgsBWiS9cnBrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=oMiPYzoO1rgsBWiS9cnBrQ"),
    SchemaV1.Business(address: "124-132 North St",areaId: "Hingham Square",desc: "Clothing store",googleId: "ChIJMUIC_0th44kRdx5Q6B_jsy4",googleRating: 5,googleReviews: 5, googleUrl: "https://maps.app.goo.gl/kqDtPYQ8LJzJBp2z6",hours: "0,11AM-4PM;1,9:30AM-5:30PM;2,9:30AM-5:30PM;3,9:30AM-5:30PM;4,9:30AM-5:30PM;5,9:30AM-5:30PM;6,9:30AM-5:30PM",imageCount: 1,likes: 0,locationLat: 42.24249,locationLng: -70.88929,name: "J.McLaughlin",nickname: "",notes: "Clothing chain stocking classic fashions for men & women, plus accessories such as belts & bags.",phone: "781-740-0833",shortName: "Clothing",type: 2,website: "https://www.jmclaughlin.com/pages/store-locator-ma-hingham",yelpCategory: "Women's Clothing",yelpId: "acquire-good-hingham",yelpPrice: "$$",yelpRating: 5,yelpReviews: 3, yelpUrl: "https://www.yelp.com/biz/acquire-good-hingham?osq=Acquire+Good"),
    SchemaV1.Business(address:"147 North St", areaId:"Hingham Square", desc:"Catholic church", googleId:"ChIJk-ocpE5h44kRerm8Eun7eoA",  googleRating: 4.9, googleReviews: 29, googleUrl: "https://maps.app.goo.gl/qWrn6QWMWDZiWocV8", hours:"0,7-11AM;1,8:30AM-5PM;2,8:30AM-5PM;3,Closed;4,8:30AM-5PM;5,8:30AM-3PM;6,Closed", imageCount: 1, likes: 0, locationLat: 42.24276, locationLng: -70.88983, name:"Saint Paul's Catholic Church", nickname:"", notes:"The Society of Catholics of Hingham purchased the property where St Paul's stands for $1,500 in 1870. The wood church, 128 feet high and with an interior of chestnut capped with black walnut, was built on the site of the oldest house in Hingham, which had been demolished in 1866.<br/><br/>In 1988, after a six-year study of more than 1,100 parishes throughout the United States, a pastoral institute at Notre Dame chose St. Paul's Church to be featured in the video, \"The Dynamic Parish.\" Churches that were deemed \"dynamic\" were community oriented churches where parishioners socialized and found spiritual enrichment and emotional support during crises. The sense of community was primarily created by St. Paul's school and its \"involved\" parent/teacher organization. The 30-minute video will be used in adult education classes to provide a diversity of leadership approaches for churches throughout the country.", phone:"781-749-0587", shortName:"Church", type: 4, website:"https://www.hinghamcatholic.org/", yelpCategory:"", yelpId:"", yelpPrice:"", yelpRating: 0, yelpReviews: 0, yelpUrl:""),
    SchemaV1.Business(address: "142 North St",areaId: "Hingham Square",desc: "Linens",googleId: "ChIJf-_GqE5h44kRafQjywayO9k",googleRating: 4.8,googleReviews: 13, googleUrl: "https://maps.app.goo.gl/xNPMkHqt8Ff1XXzq8",hours: "0,Closed;1,10AM-5PM;2,10AM-5PM;3,10AM-5PM;4,10AM-5PM;5,10AM-5PM;6,10AM-5PM",imageCount: 1,likes: 0,locationLat: 42.24238,locationLng: -70.8897,name: "La Petite Maison",nickname: "",notes: "La Petite Maison is a French inspired boutique offering the finest in imported linens, antiques and decorative accessories for the home. The Proprietor travels to France to shop the markets for unusual antique and decorative objects. The staff at La Petite Maison prides themselves in one-on-one personalized service and design consultation.<br/><br/>As soon as you walk into La Petite Maison, the scent of French soaps fill the air. The sounds of French music will bring you back to Paris. Your eyes delight in the inspiring displays throughout the shop. Customers frequently remark on the loveliness and ambiance the shop evokes. A visit will inspire you to return again and again.",phone: "(781) 741-8393",shortName: "Boutique",type: 2,website: "https://www.lapetitemaison.us/",yelpCategory: "Home Decor, Tableware",yelpId: "la-petite-maison-hingham",yelpPrice: "$$$",yelpRating: 3.6,yelpReviews: 7,yelpUrl: "https://www.yelp.com/biz/la-petite-maison-hingham"),
    SchemaV1.Business(address: "8 Main St", areaId: "Hingham Square", desc: "Barber shop", googleId: "ChIJb0KeSzth44kRRRY6yalATjw", googleRating: 5, googleReviews: 13, googleUrl: "https://maps.app.goo.gl/pCiNs1vtERKeh7vX8", hours: "0,Closed;1,Closed;2,9AM-8PM;3,9AM-8PM;4,9AM-8PM;5,9AM-8PM;6,9AM-6PM", imageCount: 1, likes: 0, locationLat: 42.24226, locationLng: -70.88916, name: "Zona Brothers Barber Shop", nickname: "", notes: "<div style=\"text-align:center;\"><strong>OUR SERVICES</strong><br/><br/>CLASSIC CUT<br/>wash, cut, neck shave, and finishing touch styling<br/><br/>BROTHERS CUT<br/>wash and condition, scalp massage, precision neck shave, steamed towel, expert cut, and finishing touch styling<br/><br/>HOT LATHER SHAVE<br/>a steamed towel, gentle facial massage with pre-shave oil, foamy shave, and a cool towel<br/><br/>BEARD TRIM<br/><br/>LINE UP<br/>detailing of neck and facial hair<br/><br/>WAXING<br/><br/>GREY BLENDING COLORING", phone: "781-871-4545", shortName: "Barber", type: 9, website: "https://zonabrothers.com/", yelpCategory: "Stylist", yelpId: "", yelpPrice: "", yelpRating: 0, yelpReviews: 0, yelpUrl: ""),
    SchemaV1.Business(address: "39 South St", areaId: "Hingham Square", desc: "Nursery", googleId: "ChIJEV42VElh44kRKUf4L2tnJfs", googleRating: 4.7, googleReviews: 85, googleUrl: "https://maps.app.goo.gl/LwUBzZkXrzLRiJFh8", hours: "0,Closed;1,9AM-5PM;2,9AM-5PM;3,9AM-5PM;4,9AM-5PM;5,9AM-5PM;6,9AM-3PM", imageCount: 1, likes: 0, locationLat: 42.24236, locationLng: -70.88902, name: "Hingham Greenery", nickname: "", notes: "Award winning Hingham Greenery, located in historic Downtown Hingham, MA has been providing outstanding service to the South Shore of Boston for over twenty years. Best Of Boston, 2013.<br/><br/>The Hingham Greenery is a unique combination of a stunning display of fresh flowers and plants from around the world, as well as a distinctive selection of interior decorations. A fresh selection of dutch flowers and local seasonal blooms are always available. We are known for our large selection of custom silk and dried arrangements, wreaths, holiday décor, plants, topiaries, and unique containers. The personalized attention we give each and every customer makes your shopping experience truly rewarding.", phone: "(781) 749-7363", shortName: "Plants", type: 2, website: "https://hinghamgreenery.com/", yelpCategory: "Florists", yelpId: "hingham-greenery-hingham", yelpPrice: "", yelpRating: 4, yelpReviews: 22, yelpUrl: "https://www.yelp.com/biz/hingham-greenery-hingham?adjust_creative=oMiPYzoO1rgsBWiS9cnBrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=oMiPYzoO1rgsBWiS9cnBrQ"),
    SchemaV1.Business(address: "33 South St", areaId: "Hingham Square", desc: "Barber", googleId: "ChIJo0RnVklh44kRB8GSaQk-urQ", googleRating: 4.7, googleReviews: 38, googleUrl: "https://maps.app.goo.gl/jg7yxnorfn9CJPnH8", hours: "0,Closed;1,Closed;2,Closed;3,Closed;4,9AM-6PM;5,9AM-6PM;6,8AM-3PM", imageCount: 1, likes: 0, locationLat: 42.24241, locationLng: -70.88886, name: "Hingham Square Barber Shop", nickname: "", notes: "\"This is an old fashioned, downtown, little barbershop in Hingham Square run by a wonderful woman named Jeannie. She works fast and always does a great job on kids and adults alike. price is very reasonable too.\"<br/><br/>Glenn S., Yelp review.", phone: "(781) 749-7771", shortName: "Barber", type: 9, website: "https://www.facebook.com/Hingham-Square-Barber-Shop-152231241460021/", yelpCategory: "Barbers", yelpId: "hingham-square-barber-shop-hingham", yelpPrice: "$", yelpRating: 5, yelpReviews: 1, yelpUrl: "https://www.yelp.com/biz/hingham-square-barber-shop-hingham?adjust_creative=oMiPYzoO1rgsBWiS9cnBrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=oMiPYzoO1rgsBWiS9cnBrQ")
    ]
  
  @Published var mapBusiness: SchemaV1.Business {
    didSet {
      updateRegion(mapBusiness.coordinates)
    }
  }
  
  let span = MKCoordinateSpan(latitudeDelta: 0.1, longitudeDelta: 0.1)
  
  init() {
    mapBusiness = SchemaV1.Business()
    let coordinates = CLLocationCoordinate2D(latitude: 42.23227,longitude: -70.89828)
    updateRegion(coordinates)
  }
  
  private func updateRegion(_ coordinates: CLLocationCoordinate2D) {
    withAnimation(.easeInOut) {
      mapCameraPosition = MapCameraPosition.region(MKCoordinateRegion(center: coordinates, span: span))
    }
  }
  
  func showNextBusiness(_ area: SchemaV1.Area, _ business: SchemaV1.Business) {    
    if business.imageCount == 0 {
      var imageCounter = 0
      while UIImage(named: ("\(area.shortName)/\(business.name)/\(imageCounter)")) != nil {
        imageCounter += 1
      }
      business.imageCount = imageCounter
    }
    
    withAnimation(.easeInOut) {
      mapBusiness = business
    }
  }

}
